In [1]:
import numpy as np
np.__version__

'1.21.5'

In [2]:
pip install numpy

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [3]:
a = np.array([1,2,3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([1, 2, 3])

In [6]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b.ndim #N-Dimension

2

In [9]:
b.shape

(3, 3)

In [11]:
_3darray = np.array([[(1,2,3),(4,5,6),(7,8,9)],[(11,12,13),(14,15,16),(17,18,19)]])

In [12]:
_3darray.ndim

3

In [13]:
_3darray.shape

(2, 3, 3)

In [14]:
_3darray

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b[0,2]

3

In [18]:
b[:,2]

array([3, 6, 9])

In [19]:
b[:,2:2]

array([], shape=(3, 0), dtype=int32)

In [27]:
d = np.linspace(1,20,5, dtype=int)
print(d)

[ 1  5 10 15 20]


In [31]:
e = np.arange(0,10,2)
print(e)

[0 2 4 6 8]


In [34]:
f = np.random.random((5,5)) #<------ size of the array
print(f)

[[0.78975423 0.77908811 0.58861139 0.70240147 0.71773583]
 [0.41750721 0.32898225 0.74002788 0.39196895 0.12525259]
 [0.24144978 0.63662434 0.79917993 0.72157473 0.47087283]
 [0.15658526 0.53027401 0.80167145 0.13241971 0.26847802]
 [0.28641842 0.27550369 0.42786904 0.20573932 0.93612447]]


In [36]:
np.random.random_integers(50,100,(3,4))

C:\Users\Sagar.Koktare\AppData\Local\Temp\ipykernel_12696\3198310918.py:1: DeprecationWarning: This function is deprecated. Please call randint(50, 100 + 1) instead
  np.random.random_integers(50,100,(3,4))


array([[73, 57, 88, 79],
       [98, 75, 96, 86],
       [90, 56, 81, 85]])

In [37]:
np.random.uniform(50,100,(3,3)) #generates floating values

array([[57.40057437, 59.42794328, 90.76785028],
       [90.78118504, 98.11381491, 98.55772425],
       [76.18135471, 60.76471678, 73.77181311]])

In [40]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
#aggregate Functions

In [45]:
Random_int = np.random.random_integers(50,100,(3,4))
print(Random_int)

[[77 54 88 62]
 [76 66 71 89]
 [87 83 81 62]]


C:\Users\Sagar.Koktare\AppData\Local\Temp\ipykernel_12696\1865278300.py:1: DeprecationWarning: This function is deprecated. Please call randint(50, 100 + 1) instead
  Random_int = np.random.random_integers(50,100,(3,4))


In [51]:
np.full((5,5),3.4)

array([[3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4]])

In [46]:
Random_int.min()

54

In [47]:
Random_int.max()

89

In [48]:
Random_int.sum()

896

In [52]:
np.mean(Random_int)

74.66666666666667

In [53]:
Random_int.mean()

74.66666666666667

In [55]:
#Math function
print(np.sqrt(Random_int))

[[8.77496439 7.34846923 9.38083152 7.87400787]
 [8.71779789 8.1240384  8.42614977 9.43398113]
 [9.32737905 9.11043358 9.         7.87400787]]


In [56]:
print(np.std(Random_int))

11.138022964402415


In [57]:
print(np.log(Random_int))

[[4.34380542 3.98898405 4.47733681 4.12713439]
 [4.33073334 4.18965474 4.26267988 4.48863637]
 [4.46590812 4.41884061 4.39444915 4.12713439]]


In [60]:
x = np.array([(1,2),(3,4)])
y = np.array([(1,2),(3,4)])

In [61]:
np.add(x,y)

array([[2, 4],
       [6, 8]])

In [62]:
np.subtract(x,y)

array([[0, 0],
       [0, 0]])

In [63]:
np.divide(x,y)

array([[1., 1.],
       [1., 1.]])

In [64]:
np.multiply(x,y)

array([[ 1,  4],
       [ 9, 16]])

In [65]:
np.remainder(x,y)

array([[0, 0],
       [0, 0]], dtype=int32)

In [66]:
z = np.array([(1,2,3),(4,5,6)])

In [67]:
z[0,1]=7

In [68]:
z

array([[1, 7, 3],
       [4, 5, 6]])